collection_name: agent
persist_directory: chroma_db
k: 3
data_path: data
md5_hex_store: md5.txt
allow_knowledge_file_type: ["txt","pdf"]


chunk_size: 200
chunk_overlap: 20
separators: ["\n\n","!",",",".","！","，","。",""]

# 混合检索配置
use_hybrid_search: true
hybrid_weights: [0.5, 0.5]          # [向量检索权重,BM25权重]